### ISSUE TITLE
NPE in EEELEventSystem.registerEvent when invoked in BaseSystem#initialize

### ISSUE THREAD

**Issue by schosin** [GMWolf/artemis-odb-eeel#2]
Adding event listeners in com.artemis.BaseSystem#initialize results in a NPE when EEELEventSystem#registerEvent is invoked before EEELEventSystem#initialize.

I added EEELPlugin using WorldConfigurationBuilder#with(ArtemisPlugin...). Since setup will only be called after all other systems are added, I am running into an NPE when trying to register event listeners before the listenerMap is initialized.

My suggestion would be to change the listenerMap in EEELEventSystem to a final field and initialize it inline. Otherwise the EEELPlugin would need to add the system with a higher priority, but even that may fail.

**Comment by absurd3** [comment]
I'll look into it. I think a good solution may be lazy initialization.

**Comment by absurd3** [comment]
I went with your suggestion and initialized the filed inline. Seems to fix the problem.
I will push the new version to maven as soon as i recover my GPG passphrase.
